### ISSUE TITLE
Is there any way to specify user network and links which a container will belong to?

### ISSUE THREAD

**Issue by vvsh** [eremetic-framework/eremetic#160]
Hi,

From examples I don't see the way to specify net and link for a container as Marathon supports.

Is there any?

Regards,
Uladzimir

**Comment by vvsh** [comment]
I see related pull request..

**Comment by vvsh** [comment]
I read the conversation for that pull request and see that you don't like the idea to support arbitrary params. But it still makes sense to me that it would be great if API supports user specified network and links.

**Comment by keis** [comment]
It should be possible to specify the network mode once #159 lands. If you need anything else this can be added as long as it's supported by the mesos api.

**Comment by vvsh** [comment]
Yes, it is all I need! Thanks
