### ISSUE TITLE
Re-register eremetic framework through marathon

### ISSUE THREAD

**Issue by zmalik** [eremetic-framework/eremetic#181]
Hi guys, 

Maybe you can help me, so the situation is that I'm deploying the eremetic using marathon. And when for some reason (scaling down) the slave which is hosting eremetic service disappear. Marathon takes care of redeploying the eremetic.

The issue I'm trying to solve here is that it is not re-registered. But registered as a new framework. And the old one remains there. I think it is supposed to stay there for 30 days, what is the default failover_timeout of the eremetic. 

What I was expecting as a normal behaviour was eremetic being re-registered.

Any ideas on how could I approach this?

**Comment by keis** [comment]
The framework id is not persisted to the database so you will get a new one everytime.

But what you can do it set the frameworkID in the config/environment (in the marathon config is great if you want to deploy a test version with the same image/config) and it should reregister using that.

**Comment by zmalik** [comment]
ok yeah makes sense, but won't it be nice to save it in the database(e.g. zk)? Like marathon, chronos etc are doing?

I'm just thinking about to avoid a patch and maybe provide a better functionality, attacking the big picture.

So right now when you scale up eremetic, from 1 to 2 instances, we have two frameworks registered.   And that would be solved with marathon config or saving in ZK the frameworkID, but let me test how would these two instances manage, AFAIK it should be transparent. And that would also solve the issue I have mentioned above.

Let me do some testing during these days as you said with marathon config as you said and then I will come back here.

**Comment by keis** [comment]
Yeah, I think that would make sense it's probably just that this setup with marathon predates the db persistance.

Running 2 instances is not really possible at all right now and as soon as the 2nd one registers in the first one is going to exit because they both use the same framework ID. Trying to make it work in a HA setup would be interesting but it's not trivial.

**Comment by zmalik** [comment]
ok got it
That would be another story and will open an issue to discuss when the need comes. 
I don't need it right now for sure but I was just daydreaming so it would be cool to present Eremetic as event-driven computing framework over mesos.  So when you have spikes you can scale crazy up and then cool down back to nearly 0 instances. Or just user unused mesos resources. And it would work for now, just that the scheduler could be a bottleneck. Sorry for going out of topic here. 

But as for now, just need to re-register nicely. Let me check as I said, zk for frameworkId.
Thanks for answering!

**Comment by zmalik** [comment]
going to close the issue, as "Re-register eremetic framework through marathon" is possible right now.
After setting **FRAMEWORK_ID** as environment variable in marathon.
