### ISSUE TITLE
Tasks randomly get stuck in TASK_QUEUED state

### ISSUE THREAD

**Issue by xEviL** [eremetic-framework/eremetic#187]
Hey guys,

just ran into an interesting issue with eremetic `v0.28.0`. 
Tasks run normally in our environment (Mesos `v.1.3.1`), so this is not related to a wrong setup of Eremetic.
Sometimes a task doesn't get beyond `TASK_QUEUED` state.

This is how it looks in eremetic logs:
```
time="2017-10-16T17:52:37Z" level=debug msg="Adding task to queue" agent_constraints=[] command="<redacted>" docker_image="<redacted>" ports=[] 
time="2017-10-16T17:52:37Z" level=debug msg="Received offers" offers=10 
time="2017-10-16T17:52:37Z" level=debug msg="Trying to find offer to launch task with" task_id=eremetic-task.0a7f3bbc-4548-41ee-90ac-12c11dd3fc36 
time="2017-10-16T17:52:37Z" level=debug msg="Preparing to launch task" offer_id=8acb9e52-ac67-43ff-8e28-614c5f6bbde6-O12193954 task_id=eremetic-task.0a7f3bbc-4548-41ee-90ac-12c11dd3fc36 
time="2017-10-16T17:52:37Z" level=debug msg="No tasks to launch. Declining offers." 
time="2017-10-16T17:52:37Z" level=debug msg="Received task status update" status="TASK_ERROR" task_id= 
time="2017-10-16T17:52:37Z" level=debug msg="No Data in task status." 
```

This is how it looks in mesos-master logs:
```
I1016 17:52:37.645774 41484 master.cpp:6532] Sending status update TASK_ERROR for task  of framework Eremetic 'ID must not be empty'
```

After re-submitting the very same task to eremetic, it worked just fine. Similar tasks (up to a parameter) has succeeded before in the same instance of eremetic 16 times, with 119 other tasks ran successfully as well.

Would be nice to safeguard somehow for tasks not being launched, otherwise the task execution can at random become unreliable. E.g. timeout when expecting a message about the task launch from Mesos or smth.

**Comment by keis** [comment]
Hey @xEviL thanks for reporting this issue.

It sounds like we're messing up the formatting of some API call. I'm guessing LaunchTasks which I see we're not checking the response of as we should.

**Comment by xEviL** [comment]
@keis could it be the message order in interactions with Mesos? On a larger system: 22/1557 tasks got stuck. Message formatting problems should be more deterministic, here it seems to be random.

**Comment by keis** [comment]
The reason I think we're messing up a message somewhere is because both eremetic and mesos is reporting the task_id as empty in a few places.

Adding a periodic status check if things we think are running would help catch this though and potentially other things. But in this case I think mesos would go "`eremetic-task.0a7f3bbc-4548-41ee-90ac-12c11dd3fc3` never heard about it"

**Comment by sachinpk** [comment]
We are experiencing this issue now but we have seen some error messages like  "Unable to check existence of database." error="zk: invalid path" on eremetic's log

**Comment by sachinpk** [comment]
After changing log level to debug we got some additional messages on log

time="2020-06-18T23:47:03Z" level=debug msg="Adding task to queue" agent_constraints="[{foo bar}]" command="<my_command>" docker_image="<my_image>" ports="[]"
time="2020-06-18T23:47:03Z" level=debug msg="Received offers" offers=18
time="2020-06-18T23:47:03Z" level=debug msg="Trying to find offer to launch task with" task_id=eremetic-task.basq1dad-0dsd5-44ad-9310-19db182b1cc2
time="2020-06-18T23:47:03Z" level=debug msg="Preparing to launch task" offer_id=0e134687-56c3-42vf-3b8a-4f3318d3c2af-O720252199 task_id=
time="2020-06-18T23:47:03Z" level=error msg="Unable to check existence of database." error="zk: invalid path"
time="2020-06-18T23:47:03Z" level=debug msg="No tasks to launch. Declining offers."
time="2020-06-18T23:47:03Z" level=debug msg="absurl was computed" path=/service/eremetic/task/eremetic-task.basq1dad-0dsd5-44ad-9310-19db182b1cc2
time="2020-06-18T23:47:03Z" level=debug msg="Received task status update" status=TASK_ERROR task_id=
time="2020-06-18T23:47:03Z" level=debug msg="Unable to read task from database" error="zk: invalid path" task_id=
time="2020-06-18T23:47:03Z" level=debug msg="No Data in task status."
time="2020-06-18T23:47:03Z" level=error msg="Unable to check existence of database." error="zk: invalid path"

**Comment by ja8zyjits** [comment]
@keis 
Hi,
I can confirm that after testing the retry method as mentioned in the pull request, this issue appeared to be resolved. We are not getting tasks stuck due to the `zk: invalid path` error since the last one month. Generally we used to get ~10 issues in a week.
