### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by hokiegeek2** [eremetic-framework/eremetic#188]
Hi Everyone,

Anyone see this and know how to fix it?

go build -ldflags "-X github.com/eremetic-framework/eremetic/version.Version=0.28.0-4-gc17592e -X github.com/eremetic-framework/eremetic/version.BuildDate=2017-10-21_01:46:00" -o eremetic github.com/eremetic-framework/eremetic/cmd/eremetic
# github.com/eremetic-framework/eremetic/server
/usr/local/go/src/github.com/eremetic-framework/eremetic/server/handler.go:215: undefined: assets.AssetDir
/usr/local/go/src/github.com/eremetic-framework/eremetic/server/handler.go:215: undefined: assets.AssetInfo
Makefile:55: recipe for target 'eremetic' failed

**Comment by hokiegeek2** [comment]
The problem is seen in the attached assets.go.txt file (needed to add the .txt extension). I don't understand when the AssetDir and AssetInfo functions are not in this file. Any ideas?
[assets.go.txt](https://github.com/eremetic-framework/eremetic/files/1403707/assets.go.txt)

**Comment by hokiegeek2** [comment]
Here's the full printout of my attempted build:

john@ace:/usr/local/go/src/github.com/eremetic-framework/eremetic$ make eremetic
glide install
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/beorn7/perks 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9!
[INFO]	--> Found desired version locally github.com/boltdb/bolt 583e8937c61f1af6513608ccc75c97b6abdf4ff9!
[INFO]	--> Found desired version locally github.com/braintree/manners 0b5e6b2c2843f4c83c2a40f96980b09cf4af733c!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew 6d212800a42e8ab5c146b8ace3490ee17e5225f9!
[INFO]	--> Found desired version locally github.com/elazarl/go-bindata-assetfs 30f82fa23fd844bd5bb1e5f216db87fd77b5eb43!
[INFO]	--> Found desired version locally github.com/gogo/protobuf 100ba4e885062801d56799d78530b73b178a78f3!
[INFO]	--> Found desired version locally github.com/golang/glog 23def4e6c14b4da8ac2ed8007337bc5eb5007998!
[INFO]	--> Found desired version locally github.com/golang/protobuf e325f446bebc2998605911c0a2650d9920361d4a!
[INFO]	--> Found desired version locally github.com/gorilla/context 08b5f424b9271eedf6f9f0ce86cb9396ed337a42!
[INFO]	--> Found desired version locally github.com/gorilla/mux bcd8bc72b08df0f70df986b97f95590779502d31!
[INFO]	--> Found desired version locally github.com/jacobsa/oglematchers 141901ea67cd4769c6800aa7bfdfc558fa22bda5!
[INFO]	--> Found desired version locally github.com/kardianos/osext ae77be60afb1dcacde03767a8c37337fad28ac14!
[INFO]	--> Found desired version locally github.com/kelseyhightower/envconfig f611eb38b3875cc3bd991ca91c51d06446afa14c!
[INFO]	--> Found desired version locally github.com/matttproud/golang_protobuf_extensions c12348ce28de40eed0136aa2b644d0ee0650e56c!
[INFO]	--> Found desired version locally github.com/mesos/mesos-go f2cd423e881bdfb0658479ca4ef433e30f4906cd!
[INFO]	--> Found desired version locally github.com/pborman/uuid a97ce2ca70fa5a848076093f05e639a89ca34d06!
[INFO]	--> Found desired version locally github.com/pmezard/go-difflib d8ed2627bdf02c080bf22230dbb337003b7aba2d!
[INFO]	--> Found desired version locally github.com/prometheus/client_golang c5b7fccd204277076155f10851dad72b76a49317!
[INFO]	--> Found desired version locally github.com/prometheus/client_model 6f3806018612930941127f2a7c6c453ba2c527d2!
[INFO]	--> Found desired version locally github.com/prometheus/common 0d0c3d572886e0f2323ed376557f9eb99b97d25b!
[INFO]	--> Found desired version locally github.com/prometheus/procfs a3bfc74126ea9e45ee5d5c6f7fc86191b7d488fb!
[INFO]	--> Found desired version locally github.com/samuel/go-zookeeper 1d7be4effb13d2d908342d349d71a284a7542693!
[INFO]	--> Found desired version locally github.com/Sirupsen/logrus 202f25545ea4cf9b191ff7f846df5d87c9382c2b!
[INFO]	--> Found desired version locally github.com/stretchr/objx cbeaeb16a013161a98496fad62933b1d21786672!
[INFO]	--> Found desired version locally github.com/stretchr/testify 69483b4bd14f5845b5a1e55bca19e954e827f1d0!
[INFO]	--> Found desired version locally golang.org/x/net 973f3f3bbd50e92b13faa6c53ec16f49b45e851c!
[INFO]	--> Found desired version locally golang.org/x/sys fb4cac33e3196ff7f507ab9b2d2a44b0142f5b5a!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b!
[INFO]	--> Found desired version locally github.com/gopherjs/gopherjs dc374d32704510cb387457180ca9d5193978b555!
[INFO]	--> Found desired version locally github.com/jtolds/gls 77f18212c9c7edc9bd6a33d383a7b545ce62f064!
[INFO]	--> Found desired version locally github.com/smartystreets/assertions 4ea54c1f28ad3ae597e76607dea3871fa177e263!
[INFO]	--> Found desired version locally github.com/smartystreets/goconvey d4c757aa9afd1e2fc1832aaab209b5794eb336e1!
[INFO]	Setting references.
[INFO]	--> Setting version for github.com/braintree/manners to 0b5e6b2c2843f4c83c2a40f96980b09cf4af733c.
[INFO]	--> Setting version for github.com/elazarl/go-bindata-assetfs to 30f82fa23fd844bd5bb1e5f216db87fd77b5eb43.
[INFO]	--> Setting version for github.com/davecgh/go-spew to 6d212800a42e8ab5c146b8ace3490ee17e5225f9.
[INFO]	--> Setting version for github.com/beorn7/perks to 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9.
[INFO]	--> Setting version for github.com/golang/glog to 23def4e6c14b4da8ac2ed8007337bc5eb5007998.
[INFO]	--> Setting version for github.com/boltdb/bolt to 583e8937c61f1af6513608ccc75c97b6abdf4ff9.
[INFO]	--> Setting version for github.com/gogo/protobuf to 100ba4e885062801d56799d78530b73b178a78f3.
[INFO]	--> Setting version for github.com/golang/protobuf to e325f446bebc2998605911c0a2650d9920361d4a.
[INFO]	--> Setting version for github.com/gorilla/context to 08b5f424b9271eedf6f9f0ce86cb9396ed337a42.
[INFO]	--> Setting version for github.com/gorilla/mux to bcd8bc72b08df0f70df986b97f95590779502d31.
[INFO]	--> Setting version for github.com/kelseyhightower/envconfig to f611eb38b3875cc3bd991ca91c51d06446afa14c.
[INFO]	--> Setting version for github.com/matttproud/golang_protobuf_extensions to c12348ce28de40eed0136aa2b644d0ee0650e56c.
[INFO]	--> Setting version for github.com/kardianos/osext to ae77be60afb1dcacde03767a8c37337fad28ac14.
[INFO]	--> Setting version for github.com/jacobsa/oglematchers to 141901ea67cd4769c6800aa7bfdfc558fa22bda5.
[INFO]	--> Setting version for github.com/mesos/mesos-go to f2cd423e881bdfb0658479ca4ef433e30f4906cd.
[INFO]	--> Setting version for github.com/pmezard/go-difflib to d8ed2627bdf02c080bf22230dbb337003b7aba2d.
[INFO]	--> Setting version for github.com/pborman/uuid to a97ce2ca70fa5a848076093f05e639a89ca34d06.
[INFO]	--> Setting version for github.com/prometheus/client_model to 6f3806018612930941127f2a7c6c453ba2c527d2.
[INFO]	--> Setting version for github.com/prometheus/common to 0d0c3d572886e0f2323ed376557f9eb99b97d25b.
[INFO]	--> Setting version for github.com/prometheus/client_golang to c5b7fccd204277076155f10851dad72b76a49317.
[INFO]	--> Setting version for github.com/prometheus/procfs to a3bfc74126ea9e45ee5d5c6f7fc86191b7d488fb.
[INFO]	--> Setting version for github.com/samuel/go-zookeeper to 1d7be4effb13d2d908342d349d71a284a7542693.
[INFO]	--> Setting version for github.com/Sirupsen/logrus to 202f25545ea4cf9b191ff7f846df5d87c9382c2b.
[INFO]	--> Setting version for github.com/stretchr/testify to 69483b4bd14f5845b5a1e55bca19e954e827f1d0.
[INFO]	--> Setting version for github.com/stretchr/objx to cbeaeb16a013161a98496fad62933b1d21786672.
[INFO]	--> Setting version for github.com/gopherjs/gopherjs to dc374d32704510cb387457180ca9d5193978b555.
[INFO]	--> Setting version for github.com/smartystreets/assertions to 4ea54c1f28ad3ae597e76607dea3871fa177e263.
[INFO]	--> Setting version for github.com/jtolds/gls to 77f18212c9c7edc9bd6a33d383a7b545ce62f064.
[INFO]	--> Setting version for github.com/smartystreets/goconvey to d4c757aa9afd1e2fc1832aaab209b5794eb336e1.
[INFO]	--> Setting version for golang.org/x/net to 973f3f3bbd50e92b13faa6c53ec16f49b45e851c.
[INFO]	--> Setting version for golang.org/x/sys to fb4cac33e3196ff7f507ab9b2d2a44b0142f5b5a.
[INFO]	--> Setting version for gopkg.in/yaml.v2 to cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b.
[INFO]	Exporting resolved dependencies...
[INFO]	--> Exporting github.com/beorn7/perks
[INFO]	--> Exporting github.com/elazarl/go-bindata-assetfs
[INFO]	--> Exporting github.com/prometheus/common
[INFO]	--> Exporting github.com/kelseyhightower/envconfig
[INFO]	--> Exporting github.com/kardianos/osext
[INFO]	--> Exporting github.com/prometheus/client_golang
[INFO]	--> Exporting github.com/jacobsa/oglematchers
[INFO]	--> Exporting github.com/pmezard/go-difflib
[INFO]	--> Exporting github.com/golang/protobuf
[INFO]	--> Exporting github.com/gogo/protobuf
[INFO]	--> Exporting github.com/davecgh/go-spew
[INFO]	--> Exporting github.com/gorilla/context
[INFO]	--> Exporting github.com/golang/glog
[INFO]	--> Exporting github.com/gorilla/mux
[INFO]	--> Exporting github.com/boltdb/bolt
[INFO]	--> Exporting github.com/matttproud/golang_protobuf_extensions
[INFO]	--> Exporting github.com/pborman/uuid
[INFO]	--> Exporting github.com/mesos/mesos-go
[INFO]	--> Exporting github.com/prometheus/client_model
[INFO]	--> Exporting github.com/braintree/manners
[INFO]	--> Exporting github.com/prometheus/procfs
[INFO]	--> Exporting github.com/samuel/go-zookeeper
[INFO]	--> Exporting github.com/Sirupsen/logrus
[INFO]	--> Exporting github.com/stretchr/objx
[INFO]	--> Exporting github.com/stretchr/testify
[INFO]	--> Exporting github.com/gopherjs/gopherjs
[INFO]	--> Exporting github.com/jtolds/gls
[INFO]	--> Exporting github.com/smartystreets/assertions
[INFO]	--> Exporting github.com/smartystreets/goconvey
[INFO]	--> Exporting golang.org/x/net
[INFO]	--> Exporting golang.org/x/sys
[INFO]	--> Exporting gopkg.in/yaml.v2
[INFO]	Replacing existing vendor dependencies
go get github.com/jteeuwen/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go get github.com/smartystreets/goconvey
go get github.com/jteeuwen/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go get github.com/smartystreets/goconvey
go get github.com/jteeuwen/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
go get github.com/smartystreets/goconvey
go build -ldflags "-X github.com/eremetic-framework/eremetic/version.Version=0.28.0-4-gc17592e -X github.com/eremetic-framework/eremetic/version.BuildDate=2017-10-21_10:41:05" -o eremetic github.com/eremetic-framework/eremetic/cmd/eremetic
# github.com/eremetic-framework/eremetic/server
server/handler.go:215: undefined: assets.AssetDir
server/handler.go:215: undefined: assets.AssetInfo
Makefile:55: recipe for target 'eremetic' failed
make: *** [eremetic] Error 2

**Comment by keis** [comment]
Does the server/assets/assets.go file get generated?

**Comment by keis** [comment]
Oh, I see you even included in the middle comment.

I think these tools are not installed with pinned versions so it's possible something has changed in upstream.

**Comment by hokiegeek2** [comment]
Gotcha, okay, any ideas as to how to proceed? I admit I am a java/scala/python guy and am just getting started with golang, so any guidance would definitely be appreciated.

Thanks

--John

**Comment by keis** [comment]
if you want to look into it I would start by looking at the go-bindata and go-bindata-assetfs projects and see what's changed and what the docs says.

Otherwise I will hopefully find some time for eremetic stuff one of these days :)

**Comment by hokiegeek2** [comment]
Okay, I fixed it. I ran the following command:
go generate github.com/eremetic-framework/eremetic/server/assets
Once I did this the AssetDir and AssetInfo functions were generated and the project built.

**Comment by keis** [comment]
that command fails for me and in the makefile we use `go generate github.com/eremetic-framework/eremetic/server` which seems to work.

`go-bindata-assetfs -version` is 3.1.0 for me. what are you on?
also go version?

**Comment by hokiegeek2** [comment]
Yeah, I don't pretend to understand why this is working the way it is. :) I
don't have access to this info now (all of this is on my home cluster),
will answer your questions later today.

--John

**Comment by hokiegeek2** [comment]
go-bindata 3.1.0 (Go runtime go1.8.3).
Copyright (c) 2010-2013, Jim Teeuwen.
**Cannot read bindata.go open bindata.go: no such file or directory**

Now...wonder if the last, bolded line explains the issue I ran into?

**Comment by keis** [comment]
Same exact versions, and same exact message that you highlighted. But I do get those functions generated.

**Comment by alde** [comment]
That error message is expected, and has always been there... and it has annoyed me forever and I haven't been able to figure out how to fix it unfortunately.

**Comment by sergi** [comment]
I had this error and the root cause was that the `eremetic` folder was not in the `GOPATH` folder. Noob mistake.

**Comment by ja8zyjits** [comment]
For people having this trouble, with `go 1.14`

Dont curl the binary instead do `go get github.com/go-bindata/go-bindata/...`

do `go generate github.com/eremetic-framework/eremetic/server`

then `make eremetic`

hope to save some of your time
