### ISSUE TITLE
deploying as docker in bridge mode on marathon not working

### ISSUE THREAD

**Issue by hokiegeek2** [eremetic-framework/eremetic#194]
Hi Everyone,

If I deploy eremetic in a docker in host network mode on marathon, it works fine. If I deploy in bridge mode, eremetic immediately goes to inactive framework status on Mesos and I don't see in the logs that eremetic ever actually registers as a framework in Mesos. The UI is accessible but, as expected, when I submit a job it remains in queued state because eremetic is not a registered Mesos framework.

I followed the [example](https://github.com/eremetic-framework/eremetic/blob/master/misc/eremetic.json) and it is not working.

Any ideas?

--John

**Comment by keis** [comment]
Could you attach the logs of eremetic with debug when launching in bridge mode? it sounds like callback port is not working this would typically be from reporting the wrong address or port

**Comment by hokiegeek2** [comment]
Hey David,

Yeah, I agree, that's what appears to be happening. I will get the logs tomorrow. Like I wrote, it's weird this is not working, because I am following the traefik example provided in the eremetic github.

**Comment by hokiegeek2** [comment]
Okay, when I switched to host networking it started working. Here's my config details:

traefik.frontend.rule=Host:eremetic.hokiegeek2.org
traefik.enable=true
traefik.port=13500

Also, I defined two port definitions, one for web, one for callback
[
   {
       "port": 10294,
       "protocol": "tcp",
       "name": "web",
       "labels": {}
   },
   {
       "port": 10295,
       "protocol": "tcp",
       "name": "callback",
       "labels": {}
   }
]
