### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by sachinpk** [eremetic-framework/eremetic#215]
Is this project still undergoing development? The master branch seems updated In June 2019 but the last release was in 2017.
It would be great if we could get the updated master released.

**Comment by ja8zyjits** [comment]
Would love to have https://github.com/eremetic-framework/eremetic/pull/189 released.

**Comment by alde** [comment]
Development has unfortunately stalled since I don't have any daily work related to mesos anymore - so it's hard to keep up to date.

I can definitely cut a new release on the latest master though.

**Comment by ja8zyjits** [comment]
This will be really helpful for all. Thanks.

**Comment by alde** [comment]
I'm also gonna see if I can dedicate some more time to maintenance if needed

**Comment by ja8zyjits** [comment]
@alde Hey it will be great if you could just push this version to docker. I can see the latest to be `docker pull alde/eremetic:latest` which was updated 3 years ago.
Once you do this, I may try to register this with the dc/os universe.

**Comment by alde** [comment]
hmm, it seems the docker push script in the ci pipeline has stopped working, will look into it

**Comment by alde** [comment]
@ja8zyjits latest has been updated

**Comment by ja8zyjits** [comment]
@alde thank you for prompt response. Will keep you posted regarding the dc/os universe update.

**Comment by ja8zyjits** [comment]
@alde the new version is now available in the dc/os universe
https://github.com/mesosphere/universe/pull/2515
