### ISSUE TITLE
x509: certificate signed by unknown authority error on  Call back

### ISSUE THREAD

**Issue by sachinpk** [eremetic-framework/eremetic#217]
Cannot send callback to URLs with https, its throwing x509: certificate signed by unknown authority error . Certificates are generated using Lets-Encrypt thus there is no issue with certificates.

 Here is the sample log from the eremetic container

time="2020-05-12T13:39:49Z" level=error msg="Unable to POST to Callback URI" callback_uri="https://myexamplesite.com/myapi/v1/eremetic_status_update/" error="Post https://myexamplesite.com/myapi/v1/eremetic_status_update/: x509: certificate signed by unknown authority" task_id=eremetic-task.xxxxxx-xxxx-xxxx-xxxx-xxxxxxx

**Comment by keis** [comment]
Hey,

That would indicate the root certs are missing for some reason.
Could you try creating a updated docker image where you add `apk add ca-certificates` to see if that works?

**Comment by sachinpk** [comment]
To fix this we need to add ca-certificates to the Dockerfile. 

https://github.com/google/go-github/issues/1049

I'd modified the command on marathon app of eremetic to "apk update && apk add ca-certificates && /marathon.sh" then issue got fixed

**Comment by ja8zyjits** [comment]
@keis we can close this issue right?
